name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Wiz CLI
      run: |
        curl -Lo wizcli https://wizcli.app.wiz.io/latest/wizcli-linux-amd64
        chmod +x wizcli
        sudo mv ./wizcli /usr/local/bin/.

    - name: Wiz CLI auth
      run: |
        wizcli auth --id ${{ secrets.WIZ_ID }} --secret ${{ secrets.WIZ_SECRET }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Wiz Directory Scan
      run: wizcli dir scan --path .

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: drawsmcgraw/container-lifecycle:${{ github.sha }}

    - name: Wiz Image Scan
      run: |
        docker pull drawsmcgraw/container-lifecycle:${{ github.sha }}
        wizcli docker scan --image drawsmcgraw/container-lifecycle:${{ github.sha }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    ###- name: Deploy to EKS
    ###  run: |
    ###    kubectl set image deployment/your-deployment your-container=$IMAGE_URI

    - name: Populate Kubernetes manifest
      run: |
        sed "s|REPLACE_WITH_SHA|${{ github.sha }}|g" k8s/app.yaml.template > k8s/app.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/app.yaml
        kubectl rollout status deployment/node-app-deployment

    - name: Get LoadBalancer IP
      id: get-lb-ip
      run: echo "LB_IP=$(kubectl get svc yourservice -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

    - name: Echo the application URL
      run: echo "Visit your application at http://$LB_IP"
